# Generated by Django 3.1.5 on 2021-01-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttype',
            old_name='type',
            new_name='atype',
        ),
    ]
