# Generated by Django 3.1.5 on 2021-02-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210126_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ambulancehub',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
