# Generated by Django 3.1.5 on 2021-02-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20210130_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='landmark',
            new_name='address',
        ),
        migrations.AddField(
            model_name='hospital',
            name='amenity',
            field=models.CharField(default='hospital', max_length=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
