# Generated by Django 3.1.5 on 2021-02-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20210206_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
