# Generated by Django 3.1.5 on 2021-02-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_auto_20210206_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='postcode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
