# Generated by Django 3.1.5 on 2021-02-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_auto_20210206_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
